# -*- coding: utf-8 -*-
"""Lista_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mulhE1JDlaDyOPNYVz4SC4PJeBrTM0_n

# Exercícios – Parte 1

## Exercício 1

Escreva um código Python que lê do teclado o nome e a idade de um usuário e imprime o ano em que o
usuário completará 100 anos.
Dica: você pode ler strings digitadas no teclado utilizando a função builtin input('mensagem'). Lembre-se de
converter números para seu respectivo tipo (int ou float) antes fazer operações aritméticas.
"""

nome = input('Insira seu nome: ')
idade = input('Insira usa idade: ')
idade = int(idade)
ano_atual = 2022
ano = 100-idade+2022;
print(f'{nome} irá completar 100 anos em {ano}.')

"""## Exercício 2

Escreva um código Python que lê do teclado um número digitado pelo usuário e imprime se ele par ou ímpar
"""

numero = input('Digite um numero: ')
numero = int(numero)
if (numero%2==0):
  print(f'{numero} é par.')
else :
  print(f'{numero} é impar.')

"""## Exercício 3

Escreva um código Python que imprime os números pares de 0 até 20 (incluso).
Dica: olhe a documentação da função range(). Mais informações no link
"""

from random import randrange
array_de_numeros = []
for numeros in range(21):
  numeros
  array_de_numeros.append(numeros)

array_de_numeros_pares = []

for elemento in array_de_numeros:
  if (elemento%2==0):
    array_de_numeros_pares.append(elemento)

array_de_numeros_pares

"""## Exercício 4

Escreva um código Python que imprime todos os números primos de 0 até 100.
"""

numeros = []
numeros_primos = []
for numero in range(0, 101):
  numeros.append(numero);

for elemento in numeros:
  if (elemento%elemento==1)

"""## Exercício 5

Escreva um código Python que lê do teclado um dia, um mês e um ano e imprime a data completa no
formato a seguir:
Exemplo: 22/10/2022
"""

dia = input('Insira o dia: ')
mes = input('Insira o mês: ')
ano = input('Insira o ano: ')

print(dia, mes, ano, sep=
      ('/'))

"""# Exercícios – Parte 2

## Exercício 1

Dada duas listas como no exemplo abaixo:
 a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
 b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
Escreve um programa que retorne o que as litas têm comum (sem repetições). O seu programa deve
funcionar para listas de qualquer tamanho.

## Exercício 2

Dada a seguinte lista:
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Faça um programa que gere uma nova lista contendo apenas números ímpares.

## Exercício 3

Peça para o usuário digitar uma palavra pelo teclado e determina se a palavra digitada é ou não um
palíndromo. Um palíndromo é uma palavra que permanece igual se lida de traz pra frente.

## Exercício 4

Dada as listas a seguir:
primeirosNomes = ['Joao', 'Douglas', 'Lucas', 'José']
sobreNomes = ['Soares', 'Souza', 'Silveira', 'Pedreira']
idades = [19, 28, 25, 31]
Faça um programa que imprima os dados na seguinte estrutura: " - está com anos"

## Exercício 5

Escreva uma função que recebe uma lista e retorna uma nova lista sem elementos duplicados. Utilize um
exemplo para testar sua função

## Exercício 6

Escreva um programa que lê o conteúdo do arquivo texto arquivo_texto.txt e imprime o seu conteúdo.
Dica: leia documentação da função open(...), link: https://docs.python.org/3/library/functions.html#open

## Exercício 7

Leia o arquivo person.json, faça o parsing e imprima seu conteúdo.
Dica: leia a documentação do pacote json, link: https://docs.python.org/3/library/json.html

## Exercício 8

Implemente a função my_map(list, f) que recebe uma lista como primeiro argumento e uma função como
segundo argumento. Esta função aplica a função recebida para cada elemento da lista recebida retorna o
resultado em uma nova lista.
Teste sua função para saber se está ok

## Exercício 9

Escreva uma função que recebe um número variável de parâmetros não nomeados e um número variado de
parâmetros nomeados e imprime o valor de cada parâmetro recebido.

## Exercício 10

Implemente a classe Lampada. A classe Lâmpada recebe um booleano no seu construtor, True se a lâmpada
estiver ligada, False caso esteja desligada. A classe Lampada possuí os seguintes métodos:
• liga(): muda o estado da lâmpada para ligada
• desliga(): muda o estado da lâmpada para desligada
• esta_ligada(): retorna verdadeiro se a lâmpada estiver ligada, falso caso contrário

## Exercício 11

Escreva um programa que leia do teclado uma sequência de número separados por vírgula (e.g. 2,4,5,6,1,6) e
imprime a soma de todos eles.

## Exercício 12

Escreve uma função que recebe como parâmetro uma lista e retorna 3 listas: a lista recebida dividida em 3
partes iguais. Teste sua implementação
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

## Exercício 13

Dado o dicionário a seguir:
speed = {'jan':47, 'feb':52, 'march':47, 'April':44, 'May':52, 'June':53, 'july':54, 'Aug':44, 'Sept':54}
Crie uma lista com todos os valores (não as chaves!) e coloque numa lista de forma que não haja valores
duplicados.

## Exercício 14

Calcule o valor mínimo, valor máximo, valor médio e a mediana da lista gerada na célula abaixo:
Obs.: Lembrem-se, para calcular a mediana a lista deve estar ordenada!

## Exercício 15

Imprima a lista da célula abaixo de trás para frente.
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
"""

