# -*- coding: utf-8 -*-
"""Lista_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuTiwjZ9Oz2jF59r5h9Z33iE0xi-1uHK
"""



"""# Exercícios – Pandas

## Exercício 1

Leia o arquivo actors.csv e faça os seguintes cálculos sobre o conjunto de dados utilizando Pandas
• O ator/atriz com maior número de filmes e o respectivo número de filmes.
• A média do número de filmes.
• O ator/atriz com a maior média por filme.
• O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.

## Exercício 2

Leia o arquivo csv googleplaystore.csv e realize as seguintes atividades sobre o dataset utilizando Pandas:
• Faça um gráfico de barras contendo os top 5 apps por número de instalação.
• Faça um gráfico de pizza (pie chart) mostrando as categorias de apps existentes no dataset
de acordo com a frequência em que elas aparecem.
• Mostre qual o app mais caro existente no dataset.
• Mostre quantos apps são classificados como “Mature 17+”.
• Mostre o top 10 apps por número de reviews bem como o respectivo número de reviews.
Ordene a lista de forma decrescente por número de reviews.

## Exercício 3

Leia o arquivo csv wines_SPA.csv e realize as seguintes atividades sobre o dataset utilizando Pandas:
• Mostre qual a vinícola (winery) que possui o maior número de reviews (num_reviews) nos
últimos 20 anos.
• Mostre quais são as 5 regiões com a média de preço mais alta e mais baixa.
• A acidez (acidity) varia entre valores até 5, mostre a média de acidez por ano em todo o
intervalo existente na coluna ano (year).
• Mostre qual vinho (wine) possui o maior número de safras em todo o intervalo existente na
coluna ano (year).

# Exercícios – NumPy

## Exercício 1

Crie um array 5x5 com a sequência 1...25 (incluso) e faça a soma dos elementos da diagonal.

## Exercício 2

Crie um array 5x5 com a sequência de números pares entre 0...50 (incluso) e faça as seguintes operações:
• Soma das linhas
• Soma das Colunas
• Média dos elementos da última linha
• Média dos elementos da última coluna

## Exercício 3

Dado o array 2D abaixo, substitua o seu maior valor por 0.
• np.random.normal(0, 3, size=(5, 5))

## Exercício 4

A partir das arrays abaixo, caso seja possível, realize o produto das mesmas:
• np.random.uniform(size=(5, 3))
• np.random.uniform(size=(3, 4))

## Exercício 5

Dado o array abaixo, converta-o para um array do tipo int32.
• np.arange(9, dtype=np.float32).reshape(3, 3)

## Exercício 6

Dado o array abaixo, some 10 em todos os elementos da última coluna.
• np.random.uniform(size=(8, 8))

## Exercício 7

Dados os dois arrays 2x4 abaixo, empilhe ambos formando um novo array 4x4.
• np.array([[0,3,4,5], [7, 10, 9, 2]])
• np.array([[1,4,9,12], [15, 22, 19, 17]])

## Exercício 8

Dado o array definido por np.arange(25).reshape(5, 5), realize as seguintes operações sem utilizar nenhum
tipo de loop (for / while):
• A média das linhas 0, 2 e 3.
• A média das colunas 0, 1 e 4.
• A soma dos elementos das duas diagonais.

## Exercício 9

Dado o array abaixo, selecione os valores Pares e todos os valores maiores que 8, seu código não deve conter
nenhum tipo de loop (for / while):
• np.arange(25).reshape(5, 5)

## Exercício 10

Dado o array 2D abaixo, substitua os 5 menores valores por -1, seu código não deve conter nenhum tipo de
loop (for / while):
• a = np.random.randint(0, 50, (5, 5))
"""